<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- Ortak ayarlar icin bkz: /Directory.Build.props -->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SahaGor.Application\SahaGor.Application.csproj" />
    <ProjectReference Include="..\SahaGor.Infrastructure\SahaGor.Infrastructure.csproj" />
    <ProjectReference Include="..\SahaGor.Domain\SahaGor.Domain.csproj" />
  </ItemGroup>

</Project>
