// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SahaGor.Infrastructure.Persistence;

#nullable disable

namespace SahaGor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SahaGorDbContext))]
    [Migration("20260918115907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EkipGorevKategorisi", b =>
                {
                    b.Property<Guid>("EkipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UzmanlikAlanlariId")
                        .HasColumnType("uuid");

                    b.HasKey("EkipId", "UzmanlikAlanlariId");

                    b.HasIndex("UzmanlikAlanlariId");

                    b.ToTable("ekip_uzmanlik_alanlari", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Birim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KurumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SilindiMi");

                    b.HasIndex("KurumId", "Ad")
                        .IsUnique();

                    b.ToTable("birimler", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Bolge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KurumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Polygon>("SinirPolygonu")
                        .IsRequired()
                        .HasColumnType("geography (Polygon,4326)");

                    b.Property<Guid?>("SorumluBirimId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.HasIndex("SilindiMi");

                    b.HasIndex("SinirPolygonu");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SinirPolygonu"), "GIST");

                    b.HasIndex("SorumluBirimId");

                    b.ToTable("bolgeler", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Ekip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BirimId")
                        .HasColumnType("uuid");

                    b.Property<Point>("GuncelKonum")
                        .HasColumnType("geography (Point,4326)");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("KonumGuncellenmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuncelKonum");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GuncelKonum"), "GIST");

                    b.HasIndex("SilindiMi");

                    b.HasIndex("BirimId", "Ad")
                        .IsUnique();

                    b.ToTable("ekipler", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevDurumGecmisi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DegisiklikZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GorevTalebiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IslemiYapanPersonelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Not")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OncekiDurum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YeniDurum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("GorevTalebiId");

                    b.HasIndex("IslemiYapanPersonelId");

                    b.HasIndex("SilindiMi");

                    b.ToTable("gorev_durum_gecmisleri", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevFotografi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Asama")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CekenPersonelId")
                        .HasColumnType("uuid");

                    b.Property<Point>("CekildigiKonum")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)");

                    b.Property<DateTime>("CekilmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GorevTalebiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SunucuyaUlasmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CekenPersonelId");

                    b.HasIndex("GorevTalebiId");

                    b.HasIndex("SilindiMi");

                    b.ToTable("gorev_fotograflari", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevKategorisi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlaCozumSuresiDakika")
                        .HasColumnType("integer");

                    b.Property<int>("SlaYanitSuresiDakika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("SilindiMi");

                    b.ToTable("gorev_kategorileri", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevTalebi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("AtananEkipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtananPersonelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtanmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BaslamaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BildirenTelefonNumarasi")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("BolgeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisKaynakReferansNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DogrulanmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("IptalZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Point>("Konum")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SlaHedefZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TamamlanmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("YolaCikmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtananEkipId");

                    b.HasIndex("AtananPersonelId");

                    b.HasIndex("BolgeId");

                    b.HasIndex("Durum");

                    b.HasIndex("KategoriId");

                    b.HasIndex("Konum");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Konum"), "GIST");

                    b.HasIndex("SilindiMi");

                    b.HasIndex("SlaHedefZamaniUtc");

                    b.ToTable("gorev_talepleri", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Kurum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("IletisimTelefonu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("SilindiMi");

                    b.ToTable("kurumlar", (string)null);
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Personel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BirimId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EkipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Eposta")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("GuncellemeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuncelleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MusaitMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturmaZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("SilindiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SilinmeZamaniUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("EkipId");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("SilindiMi");

                    b.ToTable("personeller", (string)null);
                });

            modelBuilder.Entity("EkipGorevKategorisi", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Ekip", null)
                        .WithMany()
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahaGor.Domain.Varliklar.GorevKategorisi", null)
                        .WithMany()
                        .HasForeignKey("UzmanlikAlanlariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Birim", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Kurum", "Kurum")
                        .WithMany("Birimler")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Bolge", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahaGor.Domain.Varliklar.Birim", "SorumluBirim")
                        .WithMany()
                        .HasForeignKey("SorumluBirimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kurum");

                    b.Navigation("SorumluBirim");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Ekip", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Birim", "Birim")
                        .WithMany("Ekipler")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevDurumGecmisi", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.GorevTalebi", "GorevTalebi")
                        .WithMany("DurumGecmisi")
                        .HasForeignKey("GorevTalebiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahaGor.Domain.Varliklar.Personel", null)
                        .WithMany()
                        .HasForeignKey("IslemiYapanPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GorevTalebi");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevFotografi", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Personel", "CekenPersonel")
                        .WithMany()
                        .HasForeignKey("CekenPersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahaGor.Domain.Varliklar.GorevTalebi", "GorevTalebi")
                        .WithMany("Fotograflar")
                        .HasForeignKey("GorevTalebiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CekenPersonel");

                    b.Navigation("GorevTalebi");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevTalebi", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Ekip", "AtananEkip")
                        .WithMany()
                        .HasForeignKey("AtananEkipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SahaGor.Domain.Varliklar.Personel", "AtananPersonel")
                        .WithMany()
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SahaGor.Domain.Varliklar.Bolge", "Bolge")
                        .WithMany()
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SahaGor.Domain.Varliklar.GorevKategorisi", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtananEkip");

                    b.Navigation("AtananPersonel");

                    b.Navigation("Bolge");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Personel", b =>
                {
                    b.HasOne("SahaGor.Domain.Varliklar.Birim", "Birim")
                        .WithMany("Personeller")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahaGor.Domain.Varliklar.Ekip", "Ekip")
                        .WithMany("Uyeler")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Birim");

                    b.Navigation("Ekip");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Birim", b =>
                {
                    b.Navigation("Ekipler");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Ekip", b =>
                {
                    b.Navigation("Uyeler");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.GorevTalebi", b =>
                {
                    b.Navigation("DurumGecmisi");

                    b.Navigation("Fotograflar");
                });

            modelBuilder.Entity("SahaGor.Domain.Varliklar.Kurum", b =>
                {
                    b.Navigation("Birimler");
                });
#pragma warning restore 612, 618
        }
    }
}
